### PR TITLE
Add GoogleFonts badge.

### PR DESCRIPTION
**Pull request by marcianosr**

### CODE REVIEW

**Comment by RoelN** [comment]
Fixes https://github.com/undercasetype/fraunces-minisite/issues/45

**Comment by RoelN** [comment]
No too thrilled on how this is looking on the main page:

image

Also the footer layout should probably be reshuffled to avoid this:

image

**Comment by RoelN** [comment]
@davelab6 What options do we have re: moving/delaying this badge? (cc @sponcey)

**Comment by sponcey** [comment]
I think we should implement the badge similar to how it's deployed on the Recursive minisite: https://www.recursive.design

**Comment by RoelN** [comment]
Closing this in favor on non-JS sticky version

**Pull request closed without merging**
